# Generated by Django 5.1 on 2026-02-27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("kind", models.CharField(choices=[("primary", "Primary"), ("request", "Request")], default="primary", max_length=10)),
                ("is_muted", models.BooleanField(default=False)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("last_message_preview", models.CharField(blank=True, default="", max_length=280)),
            ],
            options={
                "ordering": ["-last_message_at", "-created_at"],
                "indexes": [models.Index(fields=["kind", "last_message_at"], name="direct_mess_kind_9f1b24_idx")],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("message_type", models.CharField(choices=[("text", "Text"), ("media", "Media"), ("post", "Post")], default="text", max_length=10)),
                ("body", models.TextField(blank=True)),
                ("payload", models.JSONField(blank=True, null=True)),
                ("sequence", models.PositiveBigIntegerField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("conversation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="direct_messages.conversation")),
                ("sender", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sent_messages", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["conversation", "sequence"], name="direct_mess_convers_8c8c56_idx"),
                    models.Index(fields=["conversation", "created_at"], name="direct_mess_convers_3c00b1_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReadCursor",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_read_sequence", models.PositiveBigIntegerField(default=0)),
                ("conversation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="read_cursors", to="direct_messages.conversation")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="dm_read_cursors", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("conversation", "user")},
                "indexes": [models.Index(fields=["conversation", "user"], name="direct_mess_convers_f4ab1d_idx")],
            },
        ),
        migrations.AddField(
            model_name="conversation",
            name="participants",
            field=models.ManyToManyField(related_name="dm_conversations", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="conversation",
            name="last_message",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="direct_messages.message"),
        ),
    ]
