# Generated by Django 5.1 on 2026-02-27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("direct_messages", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInboxIndex",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("kind", models.CharField(choices=[("primary", "Primary"), ("request", "Request")], default="primary", max_length=10)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("last_message_preview", models.CharField(blank=True, default="", max_length=280)),
                ("conversation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="inbox_entries", to="direct_messages.conversation")),
                ("last_message", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="direct_messages.message")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="dm_inbox_index", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("user", "conversation")},
                "indexes": [models.Index(fields=["user", "kind", "last_message_at"], name="direct_mess_user_aa7ef9_idx")],
            },
        ),
    ]
