# Generated by Django 5.1 on 2026-02-27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("direct_messages", "0002_user_inbox_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userinboxindex",
            name="other_user",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="dm_inbox_as_other", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="userinboxindex",
            name="other_username",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="userinboxindex",
            name="other_display_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="userinboxindex",
            name="other_avatar_url",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="userinboxindex",
            name="last_message_sender",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="userinboxindex",
            name="unread_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userinboxindex",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
