# Generated by Django 5.1 on 2026-02-28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("direct_messages", "0004_direct_message_outbox"),
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectMessageMedia",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("media", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="dm_media", to="system.s3media")),
                ("message", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="media_items", to="direct_messages.message")),
            ],
            options={
                "unique_together": {("message", "media")},
                "indexes": [models.Index(fields=["message", "media"], name="direct_mess_message_2f2a71_idx")],
            },
        ),
    ]
